#!/usr/bin/env bash

msg=`basename "$0"`
lib/show_logo $msg
# echo ""
# echo "--------------------------------------------------------------"
# echo " INSTALLING JDK"
# echo "--------------------------------------------------------------"

sudo apt-get install openjdk-8-jre-headless



echo ''
echo 'JAVA_HOME variable'
echo '------------------'
if [ ${#JAVA_HOME} -le 1 ]; then
	echo "JAVA_HOME not found" ;

	read -r -p "Would you like to add the x64 path as JAVA_HOME to the /etc/profile file? [y/N] " response
	if [[ "$response" =~ ^([yY][eE][sS]|[yY])+$ ]]
	then
	    echo "export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64/jre" | sudo tee --append /etc/profile
	    echo "export PATH=$JAVA_HOME/bin:$PATH" | sudo tee --append /etc/profile
	else
	    echo "Please do this manually !!! "
	fi


else
	echo "JAVA_HOME exists already"
fi

sleep 1
