#!/usr/bin/env bash


echo ""
echo "--------------------------------------------------------------"
echo " INSTALLING GIT"
echo "--------------------------------------------------------------"
#msg=`basename "$0"`
#lib/show_logo $msg

sudo apt-get install git


echo ''
echo 'POSH-GIT'
echo '--------'


downloadfolder="$HOME/linuxdo-dl/downloads"
poshfolder="${downloadfolder}/posh-git-sh"
file="${downloadfolder}/git-prompt.sh"
url="https://github.com/lyze/posh-git-sh.git"


if [ ! -f "$file" ]
then
    #echo "$0: File '${file}' not found."
  echo "File '${file}' not found."

  echo "Creating the target directories (in your home directory)"
  mkdir -p $downloadfolder
  mkdir -p $poshfolder

	echo "Cloning the repo from url : '${url}'"
	git clone $url $poshfolder

  # echo "Making the script executable"
  # chmod u+x $file
  # ls -alh $downloadfolder

	# echo ""
	# echo "Adding the posh script to '.bashrc' file"
  # if [ -f "$file" ]
  # then
  #   cat misc/bashrc_posh-git >> ~/.bashrc
  #   echo "Reloading the '.bashrc' file"
  #   . ~/.bashrc
  # fi

else
  echo "Posh-git has been found."
fi
