#!/usr/bin/env bash

echo ""
echo "--------------------------------------------------------------"
echo " INSTALLING MISC TOOLS"
echo "--------------------------------------------------------------"
echo ""
echo "FORTUNE"
echo "-------"
sudo apt-get install fortune
echo ""
echo "COWSAY"
echo "-------"
sudo apt-get install cowsay

echo "Testing Fortune & Cowsay"
fortune | cowsay
