#!/usr/bin/env bash

url="http://download.oracle.com/otn-pub/java/jdk/8u144-b01/090f390dda5b47b9b721c7dfaa008135/jdk-8u144-linux-arm32-vfp-hflt.tar.gz"
wget $url -P $HOME

sudo mkdir /usr/java
sudo unzip ~/jdk-8u144-linux-arm32-vfp-hflt.tar.gz -d /usr/java
