#!/usr/bin/env bash

# msg=`basename "$0"`
# lib/show_logo $msg
echo ""
echo "--------------------------------------------------------------"
echo " INSTALLING ANT"
echo "--------------------------------------------------------------"
sudo apt-get install ant
echo $ANT_HOME
if [ ${#ANT_HOME} -le 1 ]; then
	echo "ANT_HOME not found" ;
	read -r -p "Would you like to add the ANT_HOME enviroment variable? [y/N] " response
	if [[ "$response" =~ ^([yY][eE][sS]|[yY])+$ ]]
	then
		echo "export ANT_HOME=/usr/bin/ant" | sudo tee --append /etc/profile
		echo "export PATH=$ANT_HOME:$PATH" | sudo tee --append /etc/profile
	else
			echo "Please do this manually !!! "
	fi

else
	echo "ANT_HOME exists already"
fi

sleep 3
