#!/usr/bin/env bash

clear

# echo '      ____              __        '
# echo '     / __ \   ____ _   / /      ___ '
# echo '    / / / /  / __ `/  / /      / _ \'
# echo '   / /_/ /  / /_/ /  / /___   /  __/'
# echo '  /_____/   \__,_/  /_____/   \___/ '
# echo ''
# echo '    +-+-+-+-+-+-+-+-+-+-+ +-+-+-+'
# echo '    |L|i|n|u|x|s|h|e|l|l| |C|L|I|'
# echo '    +-+-+-+-+-+-+-+-+-+-+ +-+-+-+'
# echo ''
# echo '  >> Author : David Lejeune'
# echo "  >> Created : 31/08/2017"
# echo ''

(clear && toilet -f slant -F gay DaLe && toilet -f digital -F gay  Linux CLI && echo "$(date '+%D %T' | toilet -f term -F border --gay)"&& fortune )


if [ $# -gt 0 ]
then
  echo ""
else
  echo "No args"
fi

echo "The number of arguments is: $#"
a=${@}
echo "The total length of all arguments is: ${#a}: "
count=0
for var in "$@"
do
    echo "The length of argument '$var' is: ${#var}"
    (( count++ ))
    (( accum += ${#var} ))
done
echo "The counted number of arguments is: $count"
echo "The accumulated length of all arguments is: $accum"



echo ' ###################################'
echo '   '$1 $2 $3 $4 $5 $6 $7 $8 $9
echo ' ###################################'
echo ''
