#!/usr/bin/env bash


echo ""
echo "--------------------------------------------------------------"
echo " INSTALLING GIT"
echo "--------------------------------------------------------------"
#msg=`basename "$0"`
#lib/show_logo $msg

sudo apt-get install git
